/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TambahPegawai.java
 *
 * Created on Jun 19, 2013, 11:38:46 AM
 */
package View;

import Model.Operator;
import Model.PNS;
import Model.SK_CPNS;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author a9uszT
 */
public class TambahPegawai extends javax.swing.JFrame {
    PNS pegawai = new PNS("-","-","-","-","-","-","-","-","-","-");
    /** Creates new form TambahPegawai */
    public TambahPegawai() {
//        Operator op = Controller.ControlData.getKoneksi().tampilOperator("P");
//        TP_Kode_Label.setText(op.getKode_operator());
//        TP_Nama_Label.setText(op.getNamaOperator());
        initComponents();
//        DU_Simpan_button.setEnabled(false);
//        DU_next_button.setEnabled(false);
//        jTabbedPane1.setEnabledAt(1, false);
//        jTabbedPane1.setEnabledAt(2, false);
//        jTabbedPane1.setEnabledAt(3, false);
//        jTabbedPane1.setEnabledAt(4, false);
//        jTabbedPane1.setEnabledAt(5, false);
//        jTabbedPane1.setEnabledAt(6, false);
        Clock clock=new Clock();
        clock.showDigitalClock(time);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Tab_PNS = new javax.swing.JTabbedPane();
        DU = new javax.swing.JPanel();
        nip_br = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        DU_NipBaru_TF = new javax.swing.JTextField();
        DU_Nama_TF = new javax.swing.JTextField();
        DU_next_button = new javax.swing.JButton();
        DU_Simpan_button = new javax.swing.JButton();
        nip_br1 = new javax.swing.JLabel();
        DU_NipLama_TF = new javax.swing.JTextField();
        DU_KabKota_TF = new javax.swing.JTextField();
        DU_RT_TF = new javax.swing.JTextField();
        DU_Alamat_TF = new javax.swing.JTextField();
        Alamat1 = new javax.swing.JLabel();
        Alamat2 = new javax.swing.JLabel();
        DU_Dukuh_TF = new javax.swing.JTextField();
        Alamat3 = new javax.swing.JLabel();
        DU_RW_TF = new javax.swing.JTextField();
        Alamat4 = new javax.swing.JLabel();
        Alamat5 = new javax.swing.JLabel();
        DU_Kecamatan_TF = new javax.swing.JTextField();
        DU_Desa_TF = new javax.swing.JTextField();
        Alamat6 = new javax.swing.JLabel();
        DU_TglLhr_Date = new com.toedter.calendar.JDateChooser();
        Alamat7 = new javax.swing.JLabel();
        DU_TmptLhr_Date = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        SK_CPNS = new javax.swing.JPanel();
        CPNS_simpan_button = new javax.swing.JButton();
        CPNS_next_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CPNS_TmpBuatSurat_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CPNS_TMTPersetujuan_Date = new com.toedter.calendar.JDateChooser();
        CPNS_NoSurat_TF = new javax.swing.JTextField();
        CPNS_nama_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CPNS_TmpLhr_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CPNS_TglSurat_Date = new com.toedter.calendar.JDateChooser();
        CPNS_Partikelir_TF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CPNS_Profesi_TF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CPNS_NmrPersetujuan_TF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CPNS_NipBaru_TF = new javax.swing.JTextField();
        CPNS_NipLama_TF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CPNS_TglLhr_Date = new com.toedter.calendar.JDateChooser();
        jLabel49 = new javax.swing.JLabel();
        CPNS_Sekolah_TF = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        CPNS_MasaKerjaBulan_TF = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        CPNS_GpBulan_TF = new javax.swing.JTextField();
        CPNS_Golongan_TF = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        CPNS_MasaKerjaTahun_TF = new javax.swing.JTextField();
        CPNS_GPdari_TF = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        CPNS_Berijazah_TF = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        CPNS_PersetujuanDr_TF = new javax.swing.JTextField();
        CPNS_TMTPartikelir_Date = new com.toedter.calendar.JDateChooser();
        jLabel73 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        SK_PangkatTerakhir = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        PT_Nama_TF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        PT_TglLhr_Date = new com.toedter.calendar.JDateChooser();
        PT_TmpLhr_TF = new javax.swing.JTextField();
        PT_NipBaru_TF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        PT_NipLama_TF = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        simpan_button2 = new javax.swing.JButton();
        next_button2 = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jDateChooser8 = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        SPTKG_Terakhir = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        SPTKG_Nama_TF = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jDateChooser9 = new com.toedter.calendar.JDateChooser();
        jTextField31 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        SPTKG_NipLama_TF = new javax.swing.JTextField();
        SPTKG_NipBaru_TF = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        simpan_button3 = new javax.swing.JButton();
        next_button3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jDateChooser10 = new com.toedter.calendar.JDateChooser();
        jLabel44 = new javax.swing.JLabel();
        SK_Karpeg = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        Karpeg_Nama_TF = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jDateChooser11 = new com.toedter.calendar.JDateChooser();
        Karpeg_NipBaru_TF = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        Karpeg_NipLama_TF = new javax.swing.JTextField();
        simpan_button4 = new javax.swing.JButton();
        next_button4 = new javax.swing.JButton();
        jTextField46 = new javax.swing.JTextField();
        Karpeg_TglLhr_Date = new com.toedter.calendar.JDateChooser();
        Surat_Nikah = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jDateChooser13 = new com.toedter.calendar.JDateChooser();
        simpan_button5 = new javax.swing.JButton();
        next_button5 = new javax.swing.JButton();
        KK = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        KK_Alamat_TF = new javax.swing.JTextField();
        KK_RT_TF = new javax.swing.JTextField();
        KK_RW_TF = new javax.swing.JTextField();
        KK_KelDesa_TF = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jTextField53 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        KK_KabKota_TF = new javax.swing.JTextField();
        KK_Kec_TF = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextField55 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        time = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TP_Nama_Label = new javax.swing.JLabel();
        TP_Kode_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 888, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tambah PNS");

        DU.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nip_br.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nip_br.setText("NIP Baru");
        DU.add(nip_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama.setText("Nama");
        DU.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        Alamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat.setText("RT");
        DU.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        DU_NipBaru_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DU_NipBaru_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DU_NipBaru_TFKeyPressed(evt);
            }
        });
        DU.add(DU_NipBaru_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 363, -1));

        DU_Nama_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DU.add(DU_Nama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 360, -1));

        DU_next_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DU_next_button.setText("Next");
        DU_next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DU_next_buttonActionPerformed(evt);
            }
        });
        DU.add(DU_next_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        DU_Simpan_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DU_Simpan_button.setText("Simpan");
        DU_Simpan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DU_Simpan_buttonActionPerformed(evt);
            }
        });
        DU.add(DU_Simpan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        nip_br1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nip_br1.setText("NIP Lama");
        DU.add(nip_br1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        DU_NipLama_TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DU_NipLama_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DU_NipLama_TFKeyPressed(evt);
            }
        });
        DU.add(DU_NipLama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 190, -1));

        DU_KabKota_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DU_KabKota_TFKeyPressed(evt);
            }
        });
        DU.add(DU_KabKota_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 190, -1));
        DU.add(DU_RT_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 60, 20));
        DU.add(DU_Alamat_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 360, -1));

        Alamat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alamat1.setText("Tempat / Tgl Lahir");
        DU.add(Alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        Alamat2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat2.setText("Kabupaten / Kota");
        DU.add(Alamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));
        DU.add(DU_Dukuh_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 130, -1));

        Alamat3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat3.setText("RW");
        DU.add(Alamat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));
        DU.add(DU_RW_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 60, -1));

        Alamat4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat4.setText("Dukuh");
        DU.add(Alamat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        Alamat5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat5.setText("Desa");
        DU.add(Alamat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));
        DU.add(DU_Kecamatan_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 190, -1));
        DU.add(DU_Desa_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 190, -1));

        Alamat6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat6.setText("Kecamatan");
        DU.add(Alamat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));
        DU.add(DU_TglLhr_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 170, -1));

        Alamat7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alamat7.setText("Alamat");
        DU.add(Alamat7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));
        DU.add(DU_TmptLhr_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 160, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("DATA UTAMA");
        DU.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 840, 30));

        Tab_PNS.addTab("Data Utama", DU);

        SK_CPNS.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        SK_CPNS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CPNS_simpan_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CPNS_simpan_button.setText("Simpan");
        CPNS_simpan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPNS_simpan_buttonActionPerformed(evt);
            }
        });
        SK_CPNS.add(CPNS_simpan_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        CPNS_next_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CPNS_next_button.setText("Next");
        CPNS_next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPNS_next_buttonActionPerformed(evt);
            }
        });
        SK_CPNS.add(CPNS_next_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nomor Surat");
        SK_CPNS.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        SK_CPNS.add(CPNS_TmpBuatSurat_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tempat ,Tanggal Surat");
        SK_CPNS.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        CPNS_TMTPersetujuan_Date.setDateFormatString("d MMM yyyy");
        SK_CPNS.add(CPNS_TMTPersetujuan_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 120, -1));
        SK_CPNS.add(CPNS_NoSurat_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 230, -1));

        CPNS_nama_TF.setEditable(false);
        SK_CPNS.add(CPNS_nama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama");
        SK_CPNS.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        SK_CPNS.add(CPNS_TmpLhr_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tempat, Tanggal Lahir");
        SK_CPNS.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        CPNS_TglSurat_Date.setDateFormatString("d MMM yyyy");
        SK_CPNS.add(CPNS_TglSurat_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, -1));
        SK_CPNS.add(CPNS_Partikelir_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Partikelir, TMT");
        SK_CPNS.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        SK_CPNS.add(CPNS_Profesi_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 230, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Profesi");
        SK_CPNS.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        SK_CPNS.add(CPNS_NmrPersetujuan_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Bulan");
        SK_CPNS.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 50, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("TMT Persetujuan");
        SK_CPNS.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        CPNS_NipBaru_TF.setEditable(false);
        SK_CPNS.add(CPNS_NipBaru_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 250, -1));

        CPNS_NipLama_TF.setEditable(false);
        SK_CPNS.add(CPNS_NipLama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("NIP Lama");
        SK_CPNS.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        CPNS_TglLhr_Date.setDateFormatString("d MMM yyyy");
        SK_CPNS.add(CPNS_TglLhr_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 110, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Sekolah/Instansi");
        SK_CPNS.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        SK_CPNS.add(CPNS_Sekolah_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 230, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel65.setText("Golongan");
        SK_CPNS.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));
        SK_CPNS.add(CPNS_MasaKerjaBulan_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 40, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel66.setText("GP Bulanan, dari");
        SK_CPNS.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));
        SK_CPNS.add(CPNS_GpBulan_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 40, -1));
        SK_CPNS.add(CPNS_Golongan_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 100, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel67.setText("%");
        SK_CPNS.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 20, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel68.setText("Tahun");
        SK_CPNS.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 50, 20));

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel69.setText("Masa Kerja");
        SK_CPNS.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));
        SK_CPNS.add(CPNS_MasaKerjaTahun_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 40, -1));
        SK_CPNS.add(CPNS_GPdari_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 170, -1));

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel70.setText("NIP baru");
        SK_CPNS.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel71.setText("Berijazah");
        SK_CPNS.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));
        SK_CPNS.add(CPNS_Berijazah_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 250, -1));

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel72.setText("Persetujuan dr");
        SK_CPNS.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));
        SK_CPNS.add(CPNS_PersetujuanDr_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 250, -1));

        CPNS_TMTPartikelir_Date.setDateFormatString("d MMM yyyy");
        SK_CPNS.add(CPNS_TMTPartikelir_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 110, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("SK CPNS");
        SK_CPNS.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 840, 30));

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel75.setText("Nmr Persetujuan");
        SK_CPNS.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        Tab_PNS.addTab("SK_CPNS", SK_CPNS);

        SK_PangkatTerakhir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nomor Surat");
        SK_PangkatTerakhir.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        PT_Nama_TF.setEditable(false);
        SK_PangkatTerakhir.add(PT_Nama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 230, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nama");
        SK_PangkatTerakhir.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Tempat Lahir");
        SK_PangkatTerakhir.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Tanggal Lahir");
        SK_PangkatTerakhir.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Pendidikan");
        SK_PangkatTerakhir.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Pangkat Lama");
        SK_PangkatTerakhir.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        SK_PangkatTerakhir.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 230, -1));

        PT_TglLhr_Date.setDateFormatString("d MMM yyyy");
        SK_PangkatTerakhir.add(PT_TglLhr_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 230, -1));
        SK_PangkatTerakhir.add(PT_TmpLhr_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        PT_NipBaru_TF.setEditable(false);
        SK_PangkatTerakhir.add(PT_NipBaru_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 230, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("NIP baru");
        SK_PangkatTerakhir.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("NIP Lama");
        SK_PangkatTerakhir.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        PT_NipLama_TF.setEditable(false);
        SK_PangkatTerakhir.add(PT_NipLama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, -1));
        SK_PangkatTerakhir.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 230, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Ruang lama");
        SK_PangkatTerakhir.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Golongan Lama");
        SK_PangkatTerakhir.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        SK_PangkatTerakhir.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 230, -1));

        simpan_button2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpan_button2.setText("Simpan");
        simpan_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_button2ActionPerformed(evt);
            }
        });
        SK_PangkatTerakhir.add(simpan_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        next_button2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next_button2.setText("Next");
        next_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_button2ActionPerformed(evt);
            }
        });
        SK_PangkatTerakhir.add(next_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));
        SK_PangkatTerakhir.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 230, -1));
        SK_PangkatTerakhir.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 230, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("TMT lama");
        SK_PangkatTerakhir.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jDateChooser7.setDateFormatString("d MMM yyyy");
        SK_PangkatTerakhir.add(jDateChooser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 230, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Pangkat Baru");
        SK_PangkatTerakhir.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));
        SK_PangkatTerakhir.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 230, -1));
        SK_PangkatTerakhir.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 230, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Golongan Baru");
        SK_PangkatTerakhir.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Ruang baru");
        SK_PangkatTerakhir.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));
        SK_PangkatTerakhir.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 230, -1));

        jDateChooser8.setDateFormatString("d MMM yyyy");
        SK_PangkatTerakhir.add(jDateChooser8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 230, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("TMT baru");
        SK_PangkatTerakhir.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Mas kerja Gol");
        SK_PangkatTerakhir.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));
        SK_PangkatTerakhir.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 230, -1));
        SK_PangkatTerakhir.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 230, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Gaji Pokok");
        SK_PangkatTerakhir.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        Tab_PNS.addTab("SK_PangkatTerakhir", SK_PangkatTerakhir);

        SPTKG_Terakhir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Nomor Surat");
        SPTKG_Terakhir.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tanggal Surat");
        SPTKG_Terakhir.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Tempat Pembuatan Surat");
        SPTKG_Terakhir.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Nama");
        SPTKG_Terakhir.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        SPTKG_Nama_TF.setEditable(false);
        SPTKG_Terakhir.add(SPTKG_Nama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 230, -1));
        SPTKG_Terakhir.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, -1));

        jDateChooser9.setDateFormatString("d MMM yyyy");
        SPTKG_Terakhir.add(jDateChooser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 230, -1));
        SPTKG_Terakhir.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 230, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("NIP Lama");
        SPTKG_Terakhir.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        SPTKG_NipLama_TF.setEditable(false);
        SPTKG_Terakhir.add(SPTKG_NipLama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, -1));

        SPTKG_NipBaru_TF.setEditable(false);
        SPTKG_Terakhir.add(SPTKG_NipBaru_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 230, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("NIP baru");
        SPTKG_Terakhir.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        simpan_button3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpan_button3.setText("Simpan");
        simpan_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_button3ActionPerformed(evt);
            }
        });
        SPTKG_Terakhir.add(simpan_button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        next_button3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next_button3.setText("Next");
        next_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_button3ActionPerformed(evt);
            }
        });
        SPTKG_Terakhir.add(next_button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Pangkat Baru");
        SPTKG_Terakhir.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        SPTKG_Terakhir.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 230, -1));
        SPTKG_Terakhir.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 230, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Golongan Baru");
        SPTKG_Terakhir.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Ruang Baru");
        SPTKG_Terakhir.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        SPTKG_Terakhir.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 230, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Sekolah");
        SPTKG_Terakhir.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));
        SPTKG_Terakhir.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 230, -1));
        SPTKG_Terakhir.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 230, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Gaji Pokok Lama");
        SPTKG_Terakhir.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("gaji Pokok Baru");
        SPTKG_Terakhir.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));
        SPTKG_Terakhir.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 230, -1));

        jDateChooser10.setDateFormatString("d MMM yyyy");
        SPTKG_Terakhir.add(jDateChooser10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 230, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("TMT baru");
        SPTKG_Terakhir.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        Tab_PNS.addTab("SPTKG_Terakhir", SPTKG_Terakhir);

        SK_Karpeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Nomor Surat");
        SK_Karpeg.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        Karpeg_Nama_TF.setEditable(false);
        SK_Karpeg.add(Karpeg_Nama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 230, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Nama");
        SK_Karpeg.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Tanggal Lahir");
        SK_Karpeg.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel50.setText("TMT CPNS");
        SK_Karpeg.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jDateChooser11.setDateFormatString("d MMM yyyy");
        SK_Karpeg.add(jDateChooser11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 230, -1));

        Karpeg_NipBaru_TF.setEditable(false);
        SK_Karpeg.add(Karpeg_NipBaru_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 230, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("NIP baru");
        SK_Karpeg.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("NIP Lama");
        SK_Karpeg.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        Karpeg_NipLama_TF.setEditable(false);
        SK_Karpeg.add(Karpeg_NipLama_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 120, -1));

        simpan_button4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpan_button4.setText("Simpan");
        simpan_button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_button4ActionPerformed(evt);
            }
        });
        SK_Karpeg.add(simpan_button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        next_button4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next_button4.setText("Next");
        next_button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_button4ActionPerformed(evt);
            }
        });
        SK_Karpeg.add(next_button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));
        SK_Karpeg.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 230, -1));

        Karpeg_TglLhr_Date.setDateFormatString("d MMM yyyy");
        SK_Karpeg.add(Karpeg_TglLhr_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 230, -1));

        Tab_PNS.addTab("SK_Karpeg", SK_Karpeg);

        Surat_Nikah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Nomor Surat");
        Surat_Nikah.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));
        Surat_Nikah.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 230, -1));
        Surat_Nikah.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 230, -1));
        Surat_Nikah.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 230, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setText("Nama Istri");
        Surat_Nikah.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("Nama Suami");
        Surat_Nikah.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("Tanggal Nikah");
        Surat_Nikah.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jDateChooser13.setDateFormatString("d MMM yyyy");
        Surat_Nikah.add(jDateChooser13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 230, -1));

        simpan_button5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpan_button5.setText("Simpan");
        simpan_button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_button5ActionPerformed(evt);
            }
        });
        Surat_Nikah.add(simpan_button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        next_button5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next_button5.setText("Next");
        next_button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_button5ActionPerformed(evt);
            }
        });
        Surat_Nikah.add(next_button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        Tab_PNS.addTab("Surat Nikah", Surat_Nikah);

        KK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel56.setText("Nama kepala keluarga");
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel8.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, -1));
        jPanel8.add(KK_Alamat_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 230, -1));
        jPanel8.add(KK_RT_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, -1));
        jPanel8.add(KK_RW_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 40, -1));
        jPanel8.add(KK_KelDesa_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60.setText("Kelurahan/Desa");
        jPanel8.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel58.setText("RT/RW");
        jPanel8.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel57.setText("Alamat");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel61.setText("Kecamatan");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel62.setText("kabupaten/Kota");
        jPanel8.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel64.setText("Kode Pos");
        jPanel8.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel63.setText("Provinsi");
        jPanel8.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));
        jPanel8.add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 230, -1));
        jPanel8.add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 230, -1));
        jPanel8.add(KK_KabKota_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 230, -1));
        jPanel8.add(KK_Kec_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 230, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel59.setText("Nomor KK");
        jPanel8.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));
        jPanel8.add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 230, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama lengkap", "NIK", "JK", "tempat Lahir", "Tanggal Lahir", "Agama", "Pendidikan", "Pekerjaan", "Status Perkawinan", "Hub Keluarga", "Kewarganegaraan", "No Paspor/Kitas", "Nama Ayah", "Nama Ibu"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1120, 120));

        jScrollPane2.setViewportView(jPanel8);

        KK.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 380));

        Tab_PNS.addTab("KK", KK);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(355, 355, 355))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab_PNS)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tab_PNS, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 215, -1, 440));

        time.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        time.setText("time");
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        jLabel5.setText("Selamat Datang,");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setText("-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        TP_Nama_Label.setText("Nama");
        getContentPane().add(TP_Nama_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 120, -1));

        TP_Kode_Label.setText("Kode");
        getContentPane().add(TP_Kode_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void DU_Simpan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DU_Simpan_buttonActionPerformed
        sebarkanNama(DU_Nama_TF.getText());
        sebarkanNIPLama(DU_NipLama_TF.getText());
        sebarkanNIPBaru(DU_NipBaru_TF.getText());
        sebarkanKeKK();
        sebarkanTTL();
        
        pegawai.setNip_baru(DU_NipBaru_TF.getText());
        pegawai.setNip_lama(DU_NipLama_TF.getText());
        pegawai.setNama_pns(DU_Nama_TF.getText());
        try {
            Controller.ControlData.getKoneksi().insertPNS(pegawai);
            JOptionPane.showMessageDialog(rootPane,"Data Utama Berhasil Disimpan");
        } catch (Exception ex) {
            Logger.getLogger(TambahPegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
        DU_next_button.setEnabled(true);
    }//GEN-LAST:event_DU_Simpan_buttonActionPerformed

    private void DU_next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DU_next_buttonActionPerformed
        Tab_PNS.setEnabledAt(1, true);
        Tab_PNS.setSelectedIndex(1);
    }//GEN-LAST:event_DU_next_buttonActionPerformed

    private void CPNS_simpan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPNS_simpan_buttonActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        SK_CPNS cpns = new SK_CPNS();
        cpns.setId_SuratCPNS(CPNS_NoSurat_TF.getText());
        cpns.setTempat_surat(CPNS_TmpBuatSurat_TF.getText());
        cpns.setTanggal_surat(sdf.format(CPNS_TglSurat_Date.getDate()));
        cpns.setNama_pemilik(CPNS_nama_TF.getText());
        cpns.setTempat_lahir(CPNS_TmpLhr_TF.getText());
        cpns.setTanggal_lahir(sdf.format(CPNS_TglLhr_Date.getDate()));
        cpns.setPartikelir(CPNS_Partikelir_TF.getText());
        cpns.setTmt_partikelir(sdf.format(CPNS_TMTPartikelir_Date.getDate()));
        cpns.setProfesi(CPNS_Profesi_TF.getText());
        cpns.setSekolah(CPNS_Sekolah_TF.getText());
        cpns.setGp_bulanan(CPNS_GpBulan_TF.getText());
        cpns.setDari_gaji(CPNS_GPdari_TF.getText());
        cpns.setMasa_kerja_tahun(CPNS_MasaKerjaTahun_TF.getText());
        cpns.setMasa_kerja_bulan(CPNS_MasaKerjaBulan_TF.getText());
        cpns.setGolongan(CPNS_Golongan_TF.getText());
        cpns.setNip_lama(CPNS_NipLama_TF.getText());
        cpns.setNip_baru(CPNS_NipBaru_TF.getText());
        cpns.setBerijazah(CPNS_Berijazah_TF.getText());
        cpns.setPersetujuan_dr(CPNS_PersetujuanDr_TF.getText());
        cpns.setNmr_persetujuan(CPNS_NmrPersetujuan_TF.getText());
        cpns.setTmt_persetujuan(sdf.format(CPNS_TMTPersetujuan_Date.getDate()));
        cpns.setKode_operator("P");
        try {
            Controller.ControlData.getKoneksi().insertCPNS(cpns);
            Controller.ControlData.getKoneksi().updatePNS("CPNS",cpns.getNip_baru(),cpns.getId_SuratCPNS());
            JOptionPane.showMessageDialog(rootPane,"Data SK CPNS Berhasil Disimpan");
        } catch (Exception ex) {
            Logger.getLogger(TambahPegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CPNS_simpan_buttonActionPerformed

    private void CPNS_next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPNS_next_buttonActionPerformed
        Tab_PNS.setEnabledAt(2, true);
        Tab_PNS.setSelectedIndex(2);
    }//GEN-LAST:event_CPNS_next_buttonActionPerformed

    private void simpan_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan_button2ActionPerformed

    private void next_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_next_button2ActionPerformed

    private void next_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_button3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_next_button3ActionPerformed

    private void simpan_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_button3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_simpan_button3ActionPerformed

    private void simpan_button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan_button4ActionPerformed

    private void next_button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_next_button4ActionPerformed

    private void simpan_button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan_button5ActionPerformed

    private void next_button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_next_button5ActionPerformed

    private void DU_NipLama_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DU_NipLama_TFKeyPressed
        int res = cekAngka(DU_NipLama_TF.getText());
        if (res == 0) {
            DU_NipLama_TF.setText("");
        }
    }//GEN-LAST:event_DU_NipLama_TFKeyPressed

    private void DU_NipBaru_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DU_NipBaru_TFKeyPressed
        int res = cekAngka(DU_NipBaru_TF.getText());
        if (res == 0) {
            DU_NipBaru_TF.setText("");
        }
    }//GEN-LAST:event_DU_NipBaru_TFKeyPressed

    private void DU_KabKota_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DU_KabKota_TFKeyPressed
        DU_Simpan_button.setEnabled(true);
    }//GEN-LAST:event_DU_KabKota_TFKeyPressed

    private int cekAngka(String isian) {
        if (!isian.matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Masukkan harus angka..!!");
            return 0;
        }
        return 1;
    }
    
    public void sebarkanNama(String nama){
        CPNS_nama_TF.setText(nama);        
        PT_Nama_TF.setText(nama);
        SPTKG_Nama_TF.setText(nama);
        Karpeg_Nama_TF.setText(nama);
    }
    
    public void sebarkanNIPLama(String nipLama){
        CPNS_NipLama_TF.setText(nipLama);
        PT_NipLama_TF.setText(nipLama);
        SPTKG_NipLama_TF.setText(nipLama);
        Karpeg_NipLama_TF.setText(nipLama);
    }
    
    public void sebarkanNIPBaru(String nipBaru){
        CPNS_NipBaru_TF.setText(nipBaru);
        PT_NipBaru_TF.setText(nipBaru);
        SPTKG_NipBaru_TF.setText(nipBaru);
        Karpeg_NipBaru_TF.setText(nipBaru);
    }
    
    public void sebarkanKeKK(){
        KK_Alamat_TF.setText(DU_Alamat_TF.getText());
        KK_RT_TF.setText(DU_RT_TF.getText());
        KK_RW_TF.setText(DU_RW_TF.getText());
        KK_KelDesa_TF.setText(DU_Desa_TF.getText());
        KK_Kec_TF.setText(DU_Kecamatan_TF.getText());
        KK_KabKota_TF.setText(DU_KabKota_TF.getText());
    }
    
    public void sebarkanTTL(){
        Date tanggal = DU_TglLhr_Date.getDate();
        String tempat = DU_TmptLhr_Date.getText();
        
        CPNS_TglLhr_Date.setDate(tanggal);
        CPNS_TmpLhr_TF.setText(tempat);
        PT_TmpLhr_TF.setText(tempat);
        PT_TglLhr_Date.setDate(tanggal);
        Karpeg_TglLhr_Date.setDate(tanggal);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new TambahPegawai().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TambahPegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Alamat1;
    private javax.swing.JLabel Alamat2;
    private javax.swing.JLabel Alamat3;
    private javax.swing.JLabel Alamat4;
    private javax.swing.JLabel Alamat5;
    private javax.swing.JLabel Alamat6;
    private javax.swing.JLabel Alamat7;
    private javax.swing.JTextField CPNS_Berijazah_TF;
    private javax.swing.JTextField CPNS_GPdari_TF;
    private javax.swing.JTextField CPNS_Golongan_TF;
    private javax.swing.JTextField CPNS_GpBulan_TF;
    private javax.swing.JTextField CPNS_MasaKerjaBulan_TF;
    private javax.swing.JTextField CPNS_MasaKerjaTahun_TF;
    private javax.swing.JTextField CPNS_NipBaru_TF;
    private javax.swing.JTextField CPNS_NipLama_TF;
    private javax.swing.JTextField CPNS_NmrPersetujuan_TF;
    private javax.swing.JTextField CPNS_NoSurat_TF;
    private javax.swing.JTextField CPNS_Partikelir_TF;
    private javax.swing.JTextField CPNS_PersetujuanDr_TF;
    private javax.swing.JTextField CPNS_Profesi_TF;
    private javax.swing.JTextField CPNS_Sekolah_TF;
    private com.toedter.calendar.JDateChooser CPNS_TMTPartikelir_Date;
    private com.toedter.calendar.JDateChooser CPNS_TMTPersetujuan_Date;
    private com.toedter.calendar.JDateChooser CPNS_TglLhr_Date;
    private com.toedter.calendar.JDateChooser CPNS_TglSurat_Date;
    private javax.swing.JTextField CPNS_TmpBuatSurat_TF;
    private javax.swing.JTextField CPNS_TmpLhr_TF;
    private javax.swing.JTextField CPNS_nama_TF;
    private javax.swing.JButton CPNS_next_button;
    private javax.swing.JButton CPNS_simpan_button;
    private javax.swing.JPanel DU;
    private javax.swing.JTextField DU_Alamat_TF;
    private javax.swing.JTextField DU_Desa_TF;
    private javax.swing.JTextField DU_Dukuh_TF;
    private javax.swing.JTextField DU_KabKota_TF;
    private javax.swing.JTextField DU_Kecamatan_TF;
    private javax.swing.JTextField DU_Nama_TF;
    private javax.swing.JTextField DU_NipBaru_TF;
    private javax.swing.JTextField DU_NipLama_TF;
    private javax.swing.JTextField DU_RT_TF;
    private javax.swing.JTextField DU_RW_TF;
    private javax.swing.JButton DU_Simpan_button;
    private com.toedter.calendar.JDateChooser DU_TglLhr_Date;
    private javax.swing.JTextField DU_TmptLhr_Date;
    private javax.swing.JButton DU_next_button;
    private javax.swing.JPanel KK;
    private javax.swing.JTextField KK_Alamat_TF;
    private javax.swing.JTextField KK_KabKota_TF;
    private javax.swing.JTextField KK_Kec_TF;
    private javax.swing.JTextField KK_KelDesa_TF;
    private javax.swing.JTextField KK_RT_TF;
    private javax.swing.JTextField KK_RW_TF;
    private javax.swing.JTextField Karpeg_Nama_TF;
    private javax.swing.JTextField Karpeg_NipBaru_TF;
    private javax.swing.JTextField Karpeg_NipLama_TF;
    private com.toedter.calendar.JDateChooser Karpeg_TglLhr_Date;
    private javax.swing.JTextField PT_Nama_TF;
    private javax.swing.JTextField PT_NipBaru_TF;
    private javax.swing.JTextField PT_NipLama_TF;
    private com.toedter.calendar.JDateChooser PT_TglLhr_Date;
    private javax.swing.JTextField PT_TmpLhr_TF;
    private javax.swing.JPanel SK_CPNS;
    private javax.swing.JPanel SK_Karpeg;
    private javax.swing.JPanel SK_PangkatTerakhir;
    private javax.swing.JTextField SPTKG_Nama_TF;
    private javax.swing.JTextField SPTKG_NipBaru_TF;
    private javax.swing.JTextField SPTKG_NipLama_TF;
    private javax.swing.JPanel SPTKG_Terakhir;
    private javax.swing.JPanel Surat_Nikah;
    private javax.swing.JLabel TP_Kode_Label;
    private javax.swing.JLabel TP_Nama_Label;
    private javax.swing.JTabbedPane Tab_PNS;
    private com.toedter.calendar.JDateChooser jDateChooser10;
    private com.toedter.calendar.JDateChooser jDateChooser11;
    private com.toedter.calendar.JDateChooser jDateChooser13;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private com.toedter.calendar.JDateChooser jDateChooser8;
    private com.toedter.calendar.JDateChooser jDateChooser9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JLabel nama;
    private javax.swing.JButton next_button2;
    private javax.swing.JButton next_button3;
    private javax.swing.JButton next_button4;
    private javax.swing.JButton next_button5;
    private javax.swing.JLabel nip_br;
    private javax.swing.JLabel nip_br1;
    private javax.swing.JButton simpan_button2;
    private javax.swing.JButton simpan_button3;
    private javax.swing.JButton simpan_button4;
    private javax.swing.JButton simpan_button5;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
